FROM viucomlg/pimcore-php:%%PHP_VERSION%%-%%PHP_DISTRO%%-%%VARIANT%%

RUN apt-get update && \
    apt-get install -yf \
        supervisor && \
    rm -rf /var/lib/apt/lists/*

COPY supervisor/supervisord.conf /etc/supervisor/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord"]