name: Build docker images

on:
  schedule:
    - cron:  '0 18 * * *'
  push:
    branches:
      - main

env:
  APACHE_REPOSITORY: viucom/pimcore-apache
  PHP_REPOSITORY: viucom/pimcore-php
  COMPOSER_VERSION: 2.2

jobs:
  build-apache:
    name: "Build Apache image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: apache
          push: true
          tags: ${{ env.APACHE_REPOSITORY }}:2.4-alpine
  
  build-php:
    name: "Build PHP fpm images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['full', 'slim']
        php_version: ['8.0', '8.1']
        php_distro: ['bullseye']
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: run update script
        env:
          php_version: ${{ matrix.php_version }}
          php_distro: ${{ matrix.php_distro }}
          composer_version: ${{ env.COMPOSER_VERSION }}
        working-directory: ./php
        run: ./generate.sh ${{ matrix.variant }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: php
          push: true
          tags: ${{ env.PHP_REPOSITORY }}:${{ matrix.php_version }}-${{ matrix.php_distro }}-${{ matrix.variant }}