name: Build docker images

on:
  schedule:
    - cron:  '0 18 * * *'
  push:
    branches:
      - main

jobs:
  build-apache:
    name: "Build Apache image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: apache
          push: true
          tags: viucomlg/pimcore-apache:2.4-alpine
  
  build-php:
    name: "Build PHP fpm images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['full', 'slim']
        php_version: ['8.0']
        php_distro: ['bullseye']
        composer_version: ['2.2']
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: run update script
        env:
          php_version: ${{ matrix.php_version }}
          php_distro: ${{ matrix.php_distro }}
          composer_version: ${{ matrix.composer_version }}
        working-directory: ./php
        run: ./generate.sh ${{ matrix.variant }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: php
          push: true
          tags: viucomlg/pimcore-php:${{ matrix.php_version }}-${{ matrix.php_distro }}-${{ matrix.variant }}

  build-php-supervisor:
    needs: build-php
    name: "Build PHP supervisor images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['full', 'slim']
        php_version: ['8.0']
        php_distro: ['bullseye']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: run update script
        env:
            php_version: ${{ matrix.php_version }}
            php_distro: ${{ matrix.php_distro }}
            variant: ${{ matrix.variant }}
        working-directory: ./php
        run: ./generate.sh supervisor

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: php
          push: true
          tags: viucomlg/pimcore-php:${{ matrix.php_version }}-${{ matrix.php_distro }}-${{ matrix.variant }}-supervisor